import {useEffect,useRef,useState} from 'react';import {convertFileSrc,invoke} from '@tauri-apps/api/core';import {editorRange,formatMediaTime,frameStep,parseMediaTime} from '../../../media';import type {MediaInfo} from '../../../types/media';import {PlaybackControls} from './PlaybackControls';import {TimelineEditor} from './TimelineEditor';import {ThumbnailTimeline} from './ThumbnailTimeline';import {RangeSelector} from './RangeSelector';
export function VideoPreview({info,startText,endText,change}:{info:MediaInfo;startText:string;endText:string;change:(start:string,end:string)=>void}){
 const video=useRef<HTMLVideoElement>(null),segment=useRef(false),reverse=useRef<ReturnType<typeof setInterval>|null>(null),[session]=useState(()=>`editor-${Date.now()}-${Math.random().toString(36).slice(2)}`),[src,setSrc]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[playing,setPlaying]=useState(false),[current,setCurrent]=useState(0),[proxy,setProxy]=useState(false);
 const duration=info.duration??0,frame=frameStep(info.videos.find(v=>!v.attachedPicture)?.fps);let start=0,end=duration;try{[start,end]=editorRange(parseMediaTime(startText),parseMediaTime(endText),duration);}catch{}
 const stopReverse=()=>{if(reverse.current)clearInterval(reverse.current);reverse.current=null;};
 const cursor=()=>video.current?.currentTime??current;
 const seek=(time:number)=>{if(video.current)video.current.currentTime=Math.max(0,Math.min(duration,time));};
 const set=(s:number,e:number)=>{const range=editorRange(s,e,duration);change(formatMediaTime(range[0]),formatMediaTime(range[1]));};
 const toggle=()=>{stopReverse();segment.current=false;if(!video.current)return;if(video.current.paused)void video.current.play().catch(e=>setError(String(e)));else video.current.pause();};
 useEffect(()=>{let alive=true;setBusy(true);setError('');void invoke<string>('preview_media',{path:info.path,session,proxy}).then(path=>{if(alive)setSrc(convertFileSrc(path));}).catch(e=>{if(alive)setError(String(e));}).finally(()=>{if(alive)setBusy(false);});return()=>{alive=false;};},[info.path,session,proxy]);
 useEffect(()=>()=>{stopReverse();void invoke('cancel_media_preview',{session}).catch(()=>{});},[session]);
 useEffect(()=>{const hidden=()=>{if(document.hidden){video.current?.pause();stopReverse();}};document.addEventListener('visibilitychange',hidden);return()=>document.removeEventListener('visibilitychange',hidden);},[]);
 return <section className="visual-editor" tabIndex={0} aria-label="可视化裁剪编辑器" onKeyDown={e=>{if((e.target as HTMLElement).closest('input,select,textarea,button')||e.ctrlKey||e.altKey||e.metaKey)return;const key=e.key.toLowerCase();if(![' ','i','o','j','k','l','arrowleft','arrowright'].includes(key))return;e.preventDefault();if(key===' ')toggle();else if(key==='i')set(cursor(),end);else if(key==='o')set(start,cursor());else if(key==='k'){stopReverse();video.current?.pause();}else if(key==='l'){stopReverse();void video.current?.play().catch(e=>setError(String(e)));}else if(key==='j'){video.current?.pause();stopReverse();reverse.current=setInterval(()=>{const v=video.current;if(v&&v.currentTime>0)seek(v.currentTime-.1);else stopReverse();},100);}else{stopReverse();video.current?.pause();seek(cursor()+(key==='arrowleft'?-1:1)*(e.shiftKey?(frame??0):1));}}}>
 <div className="video-preview">{src&&<video ref={video} src={src} preload="metadata" playsInline onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onTimeUpdate={()=>{const t=video.current?.currentTime??0;setCurrent(t);if(segment.current&&t>=end){video.current?.pause();seek(end);segment.current=false;}}} onError={()=>setError('此格式无法直接预览，请生成兼容预览代理。导出仍使用原文件。')}/>} {!src&&<span>{busy?'正在准备预览…':'视频预览'}</span>}</div>
 <div className="preview-caption"><strong>{formatMediaTime(current)} <span>/ {formatMediaTime(duration)}</span></strong><span>{proxy?'兼容预览 · 原文件导出':'原始视频预览'}{frame?` · ${(1/frame).toFixed(3)} FPS`:' · 未知 FPS，逐帧不可用'}</span></div>
 <PlaybackControls playing={playing} toggle={toggle} seek={d=>{stopReverse();seek(cursor()+d);}} frame={frame} step={d=>{stopReverse();video.current?.pause();seek(cursor()+d*(frame??0));}}/>
 {error&&<p className="error-text" role="alert">{error}</p>}<div className="range-actions"><button className="secondary" disabled={!src||busy||duration<=0} onClick={()=>{stopReverse();seek(start);segment.current=true;void video.current?.play().catch(e=>setError(String(e)));}}>预览裁剪片段</button><button className="text-button" disabled={busy||proxy} onClick={()=>setProxy(true)}>{busy?'正在生成预览…':'生成兼容预览代理'}</button></div>
 {duration>0&&<><TimelineEditor duration={duration} current={current} start={start} end={end} seek={seek} set={set}/><ThumbnailTimeline path={info.path} session={session} duration={duration} seek={seek}/><RangeSelector start={start} end={end} current={current} getCurrent={cursor} set={set}/></>}<p className="help">聚焦编辑器：Space 播放/暂停 · I/O 入出点 · J 倒向寻帧 · K 暂停 · L 播放 · ←/→ 1 秒 · Shift + ←/→ 逐帧</p>
 </section>;
}
