import {useCallback,useEffect,useRef,useState} from 'react';
import {invoke,isTauri} from '@tauri-apps/api/core';
import {listen} from '@tauri-apps/api/event';
import {getCurrentWebviewWindow} from '@tauri-apps/api/webviewWindow';
import {open} from '@tauri-apps/plugin-dialog';
import {FileVideo,FolderOpen,Upload,RefreshCw,Scissors,Music2,Camera,ArrowRightLeft,Loader2,ChevronLeft,ChevronRight} from 'lucide-react';
import {canUseOperation,createMediaRequest,mediaParentDirectory,displayMediaPath,formatsFor,formatMediaTime,isCurrentProbe,parseMediaTime} from '../media';
import type {MediaForm,MediaInfo,MediaOperation,MediaSnapshot,OutputFormat} from '../types/media';
import {MediaInfoPanel} from '../components/media/MediaInfoPanel';
import {MediaTaskRow} from '../components/media/MediaTaskRow';
const tools=[{id:'transcode',title:'格式转换',icon:ArrowRightLeft},{id:'remux',title:'极速无损转换',icon:RefreshCw},{id:'trim',title:'视频裁剪',icon:Scissors},{id:'extractAudio',title:'提取音频',icon:Music2},{id:'screenshot',title:'视频截图',icon:Camera}] as const;
const initialForm:MediaForm={operation:'transcode',outputFormat:'mp4',quality:'balanced',videoCodec:'h264',audioCodec:'aac',crf:23,height:0,fps:0,audioBitrate:320,start:'00:00:00.000',end:'00:00:00.000',trimMode:'accurate',copyAudio:false,advanced:false};
const errorText=(e:unknown)=>typeof e==='string'?e:e instanceof Error?e.message:'操作未完成，请重试';
export default function MediaToolsPage({notify}:{notify:(message:string)=>void}){
 const [snapshot,setSnapshot]=useState<MediaSnapshot>({tasks:[],ready:false,error:null});
 const [info,setInfo]=useState<MediaInfo|null>(null),[form,setForm]=useState<MediaForm>(initialForm),[directory,setDirectory]=useState(''),[probing,setProbing]=useState(false),[error,setError]=useState(''),[dragging,setDragging]=useState(false),[adding,setAdding]=useState(false),[listPage,setListPage]=useState(1);
 const probeId=useRef(0),alive=useRef(true);
 const change=<K extends keyof MediaForm>(key:K,value:MediaForm[K])=>setForm(f=>({...f,[key]:value}));
 const selectFile=useCallback(async(path:string)=>{
 const id=++probeId.current;setProbing(true);setError('');setInfo(null);
 try {const result=await invoke<MediaInfo>('probe_media',{path});if(!alive.current||!isCurrentProbe(id,probeId.current))return;setInfo(result);setDirectory(mediaParentDirectory(result.path));setForm({...initialForm,end:formatMediaTime(result.duration??0),operation:canUseOperation(result,'transcode')?'transcode':'extractAudio',outputFormat:canUseOperation(result,'transcode')?'mp4':'mp3'});}
 catch(e){if(alive.current&&isCurrentProbe(id,probeId.current))setError(errorText(e));}
 finally {if(alive.current&&isCurrentProbe(id,probeId.current))setProbing(false);}
 },[]);
 useEffect(()=>{
 let mounted=true,receivedSnapshot=false;alive.current=true;const stops:(()=>void)[]=[];
 if(!isTauri()){setError('请在 Windows 桌面软件中使用媒体工具');return;}
 const setup=async()=>{
 const stop=await listen<MediaSnapshot>('media-snapshot-updated',e=>{if(mounted){receivedSnapshot=true;setSnapshot(e.payload);}});if(!mounted)stop();else stops.push(stop);
 const drop=await getCurrentWebviewWindow().onDragDropEvent(e=>{if(!mounted)return;setDragging(e.payload.type==='over'||e.payload.type==='enter');if(e.payload.type==='drop'){setDragging(false);if(e.payload.paths.length!==1){setError('首版一次处理一个文件，请只拖入一个媒体文件');return;}void selectFile(e.payload.paths[0]);}});if(!mounted)drop();else stops.push(drop);
 const state=await invoke<MediaSnapshot>('get_media_snapshot');if(mounted&&!receivedSnapshot)setSnapshot(state);
 };void setup().catch(e=>setError(errorText(e)));
 return()=>{mounted=false;alive.current=false;++probeId.current;stops.forEach(stop=>stop());};
 },[selectFile]);
 const choose=async()=>{try{if(!isTauri())throw new Error('请在 Windows 桌面软件中选择文件');const path=await open({multiple:false,directory:false,filters:[{name:'媒体文件',extensions:['mp4','mkv','mov','webm','avi','m4v','mp3','aac','flac','wav','m4a','opus','ogg','wma','wmv','ts']},{name:'全部文件',extensions:['*']}]});if(typeof path==='string')await selectFile(path);}catch(e){setError(errorText(e));}};
 const chooseDirectory=async()=>{try{const path=await open({directory:true,multiple:false});if(typeof path==='string')setDirectory(path);}catch(e){setError(errorText(e));}};
 const chooseTool=(operation:MediaOperation)=>setForm(f=>({...f,operation,outputFormat:formatsFor(operation)[0],videoCodec:'h264',audioCodec:'aac',advanced:false}));
 const act=async(command:string,args:Record<string,unknown>)=>{try{await invoke(command,args);}catch(e){notify(errorText(e));}};
 const submit=async()=>{if(!info)return;setError('');setAdding(true);try{const request=createMediaRequest(info,form,directory);await invoke('create_media_task',{request});notify('已加入媒体处理队列');}catch(e){setError(errorText(e));}finally{setAdding(false);}};
 let fragment='';try{if(form.operation==='trim'){const length=parseMediaTime(form.end??'')-parseMediaTime(form.start??'');fragment=length>0?formatMediaTime(length):'请设置有效时间';}}catch{fragment='请设置有效时间';}
 const videoOptions=form.operation==='transcode'||form.operation==='trim'&&form.trimMode==='accurate';
 const items=[...snapshot.tasks].reverse(),pages=Math.max(1,Math.ceil(items.length/50)),page=Math.min(listPage,pages);
 return <div className="media-workspace">{snapshot.error&&<div className="error-panel" role="alert">{snapshot.error}</div>}
 <section className={`media-drop ${dragging?'dragging':''} ${info?'compact':''}`} aria-label="媒体文件选择区域"><span className="media-drop-icon"><Upload size={info?20:30} aria-hidden="true"/></span><div><h2>{info?'选择其他媒体文件':'把媒体文件拖到这里'}</h2><p>{info?'一次处理一个文件，原文件始终保留。':'MP4、MKV、MOV、WebM、音频文件及其他常见媒体格式'}</p></div><button className="primary" disabled={probing||!snapshot.ready} onClick={()=>void choose()}>{probing?<Loader2 size={17} className="spin" aria-hidden="true"/>:<FolderOpen size={17} aria-hidden="true"/>}{probing?'正在分析':'选择媒体文件'}</button>{!snapshot.ready&&!snapshot.error&&<p className="help">正在校验媒体组件…</p>}</section>
 {error&&<div className="error-panel" role="alert"><strong>操作未完成</strong><p>{error}</p></div>}{probing&&<p role="status">正在读取媒体信息，请稍候…</p>}
 {info&&<><MediaInfoPanel info={info}/><div className="media-tools" role="tablist" aria-label="媒体操作">{tools.map(({id,title,icon:Icon})=><button key={id} role="tab" aria-selected={form.operation===id} aria-controls="media-tool-panel" disabled={!canUseOperation(info,id)} title={!canUseOperation(info,id)?id==='extractAudio'?'文件没有音轨':'文件没有可处理的视频流':undefined} className={form.operation===id?'active':''} onClick={()=>chooseTool(id)}><Icon size={19} aria-hidden="true"/>{title}</button>)}</div>
 <section className="media-operation-card" id="media-tool-panel" role="tabpanel" aria-label={tools.find(t=>t.id===form.operation)?.title}><div className="media-operation-heading"><h2>{tools.find(t=>t.id===form.operation)?.title}</h2><span className="help">{form.operation==='remux'?'保留全部兼容音视频和字幕轨道':'默认使用第一条对应轨道'}</span></div>
 {form.operation==='remux'&&<p className="help">不重新编码视频或音频，画质不变。目标容器不支持的轨道会阻止操作，不会静默丢弃。</p>}
 <div className="media-form-grid"><label>目标格式<select value={form.outputFormat} onChange={e=>change('outputFormat',e.target.value as OutputFormat)}>{formatsFor(form.operation).map(f=><option key={f} value={f} disabled={f==='webm'&&form.operation!=='remux'&&!(form.operation==='trim'&&form.trimMode==='fast')}>{f.toUpperCase()}{f==='webm'?' · 仅无损封装':''}</option>)}</select></label>
 {form.operation==='extractAudio'&&<><label>音频模式<select value={form.copyAudio?'copy':'encode'} onChange={e=>change('copyAudio',e.target.value==='copy')}><option value="encode">转为目标编码</option><option value="copy">保持原始编码（需容器兼容）</option></select></label>{!form.copyAudio&&!['wav','flac'].includes(form.outputFormat)&&<label>音频码率<select value={form.audioBitrate} onChange={e=>change('audioBitrate',Number(e.target.value))}>{[128,192,256,320].map(n=><option key={n} value={n}>{n} kbps{n===320?' · 默认':''}</option>)}</select></label>}</>}
 {form.operation==='screenshot'&&<label>截图时间<input aria-label="截图时间" value={form.start} placeholder="00:00:10.500" onChange={e=>change('start',e.target.value)}/></label>}
 {form.operation==='trim'&&<><label>开始时间<input aria-label="开始时间" value={form.start} onChange={e=>change('start',e.target.value)} placeholder="00:01:00.000"/></label><label>结束时间<input aria-label="结束时间" value={form.end} onChange={e=>change('end',e.target.value)} placeholder="00:02:00.000"/></label></>}
 </div>
 {form.operation==='trim'&&<><p className="media-fragment">片段长度 <strong>{fragment}</strong></p><fieldset className="media-options"><legend>裁剪模式</legend><label><input type="radio" name="trim-mode" checked={form.trimMode==='fast'} onChange={()=>change('trimMode','fast')}/><span>极速无损裁剪<small>快速，切点可能受关键帧影响</small></span></label><label><input type="radio" name="trim-mode" checked={form.trimMode==='accurate'} onChange={()=>setForm(f=>({...f,trimMode:'accurate',outputFormat:f.outputFormat==='webm'?'mp4':f.outputFormat,videoCodec:'h264'}))}/><span>精确裁剪<small>重新编码，时间点更准确</small></span></label></fieldset></>}
 {videoOptions&&<><fieldset className="media-options"><legend>质量</legend>{([{id:'high',text:'最高质量'},{id:'balanced',text:'平衡'},{id:'small',text:'更小体积'}] as const).map(q=><label key={q.id}><input type="radio" name="media-quality" checked={form.quality===q.id} onChange={()=>change('quality',q.id)}/><span>{q.text}</span></label>)}</fieldset><label className="check-label media-advanced-toggle"><input type="checkbox" checked={form.advanced} onChange={e=>change('advanced',e.target.checked)}/>展开高级选项</label>
 {form.advanced&&<div className="media-form-grid advanced-fields"><label>视频编码<select value={form.videoCodec} onChange={e=>change('videoCodec',e.target.value as MediaForm['videoCodec'])}><option value="h264">H.264 · 兼容优先</option><option value="hevc">H.265 / HEVC</option>{form.operation==='transcode'&&<option value="copy">保持原始编码 / Copy</option>}</select></label><label>分辨率<select disabled={form.videoCodec==='copy'} value={form.height} onChange={e=>change('height',Number(e.target.value))}><option value={0}>保持原始</option>{[720,1080,2160].map(n=><option key={n} value={n}>最高 {n}p</option>)}</select></label><label>帧率<select disabled={form.videoCodec==='copy'} value={form.fps} onChange={e=>change('fps',Number(e.target.value))}><option value={0}>保持原始</option>{[24,25,30,60].map(n=><option key={n} value={n}>{n} FPS</option>)}</select></label><label>质量 CRF<input type="number" min={0} max={51} step={1} disabled={form.videoCodec==='copy'} value={form.crf} onChange={e=>change('crf',Number(e.target.value))}/></label><label>音频编码<select value={form.audioCodec} onChange={e=>change('audioCodec',e.target.value as MediaForm['audioCodec'])}><option value="aac">AAC</option><option value="mp3">MP3</option><option value="opus">Opus（MKV）</option><option value="copy">保持原始编码 / Copy</option></select></label><label>音频码率<select disabled={form.audioCodec==='copy'} value={form.audioBitrate} onChange={e=>change('audioBitrate',Number(e.target.value))}>{[128,192,256,320].map(n=><option key={n} value={n}>{n} kbps</option>)}</select></label></div>}</>}
 {form.operation==='extractAudio'&&<p className="help">转换为更高码率不会提升原始音频的音质。无损提取需原始编码与目标格式兼容。</p>}
 <label className="field-label">保存目录</label><div className="input-with-button"><input aria-label="媒体保存目录" readOnly value={displayMediaPath(directory)}/><button className="secondary" onClick={()=>void chooseDirectory()}><FolderOpen size={16} aria-hidden="true"/>更改位置</button></div>
 <div className="media-submit"><p className="help">原文件保留，同名结果自动编号。</p><button className="primary" disabled={adding||!snapshot.ready} onClick={()=>void submit()}>{adding?<Loader2 size={17} className="spin" aria-hidden="true"/>:<FileVideo size={17} aria-hidden="true"/>}{adding?'正在加入队列':form.operation==='screenshot'?'截取当前帧':'开始处理'}</button></div></section></>}
 <section className="media-queue" aria-label="媒体处理任务"><div className="list-header"><div className="list-title"><h2>媒体任务</h2><span>{items.length}</span></div><span className="help">一次处理 1 个任务 · 关闭窗口后继续</span></div>{items.length?items.slice((page-1)*50,page*50).map(task=><MediaTaskRow key={task.id} task={task} act={act}/>):<div className="media-queue-empty"><p>处理任务会显示在这里</p><span>选择文件，完成后直接打开结果。</span></div>}{pages>1&&<div className="media-pagination"><button className="secondary" disabled={page<=1} onClick={()=>setListPage(page-1)} aria-label="媒体任务上一页"><ChevronLeft size={16}/></button><span>{page} / {pages}</span><button className="secondary" disabled={page>=pages} onClick={()=>setListPage(page+1)} aria-label="媒体任务下一页"><ChevronRight size={16}/></button></div>}</section></div>;
}
