import {FileVideo,FileAudio} from 'lucide-react';
import {displayMediaPath,formatMediaTime,mediaBitrate,mediaBytes} from '../../media';
import type {MediaInfo} from '../../types/media';
export function MediaInfoPanel({info}:{info:MediaInfo}){
 const v=info.videos.find(v=>!v.attachedPicture),a=info.audios[0];const Icon=v?FileVideo:FileAudio;
 return <section className="media-info-card"><div className="media-file-title"><span className="media-file-icon"><Icon size={28} aria-hidden="true"/></span><div><h2>{info.fileName}</h2><p title={displayMediaPath(info.path)}>{displayMediaPath(info.path)}</p></div></div><dl className="media-facts"><div><dt>时长</dt><dd>{formatMediaTime(info.duration)}</dd></div><div><dt>文件大小</dt><dd>{mediaBytes(info.size)}</dd></div><div><dt>容器</dt><dd>{info.container||'未知'}</dd></div><div><dt>总码率</dt><dd>{mediaBitrate(info.bitrate)}</dd></div>{v&&<div><dt>视频</dt><dd>{v.width&&v.height?`${v.width} × ${v.height}`:'分辨率未知'} · {v.codec.toUpperCase()}</dd><dd>{v.fps?.toFixed(3)??'未知'} FPS · {v.bitDepth?`${v.bitDepth}-bit`:'位深未知'}</dd></div>}{a&&<div><dt>音频</dt><dd>{a.codec.toUpperCase()} {a.profile} · {a.sampleRate?`${a.sampleRate/1000} kHz`:'采样率未知'}</dd><dd>{a.channelLayout||`${a.channels??'?'} 声道`} · {mediaBitrate(a.bitrate)}</dd></div>}</dl>
 <details className="media-track-details"><summary>完整媒体信息 · {info.videos.length} 视频 / {info.audios.length} 音频 / {info.subtitles.length} 字幕</summary><div className="media-track-content">
 {info.videos.map(s=><div className="media-track" key={s.index}><strong>视频轨道 {s.index} {s.attachedPicture?'（封面）':''}</strong><p>{s.codec} / {s.profile??'Profile 未知'} · {s.width??'?'} × {s.height??'?'} · {s.fps?.toFixed(3)??'?'} FPS · {s.pixelFormat??'像素格式未知'} · {s.bitDepth??'?'}-bit · {mediaBitrate(s.bitrate)}</p><Metadata tags={s.metadata}/></div>)}
 {info.audios.map(s=><div className="media-track" key={s.index}><strong>音频轨道 {s.index}</strong><p>{s.codec} / {s.profile??'Profile 未知'} · {s.sampleRate??'?'} Hz · {s.channels??'?'} 声道 · {s.channelLayout??'布局未知'} · {mediaBitrate(s.bitrate)}</p><Metadata tags={s.metadata}/></div>)}
 {info.subtitles.map(s=><div className="media-track" key={s.index}><strong>字幕轨道 {s.index}</strong><p>{s.codec} · {s.language??'语言未知'}</p><Metadata tags={s.metadata}/></div>)}<Metadata tags={info.metadata}/>{info.otherStreams>0&&<p>另有 {info.otherStreams} 条其他类型轨道，无损封装会先检查是否支持。</p>}</div></details></section>;
}
function Metadata({tags}:{tags:Record<string,string>}){return Object.keys(tags).length?<dl className="media-metadata">{Object.entries(tags).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>:null;}
