import {Check,Loader2,X,FolderOpen,Play,RefreshCw} from 'lucide-react';
import {displayMediaPath,formatMediaTime} from '../../media';
import type {MediaTask} from '../../types/media';
const labels={queued:'等待中',probing:'分析中',processing:'处理中',interrupted:'已中断',completed:'已完成',failed:'处理失败',cancelled:'已取消'};
const operations={remux:'无损封装',transcode:'格式转换',compress:'视频压缩',trim:'视频裁剪',extractAudio:'提取音频',screenshot:'视频截图',subtitleConvert:'字幕转换',subtitleMux:'外挂字幕',subtitleBurn:'字幕烧录'};
export function MediaTaskRow({task,act}:{task:MediaTask;act:(command:string,args:Record<string,unknown>)=>Promise<void>}){
 const busy=['queued','probing','processing'].includes(task.status);
 const retry=['failed','cancelled','interrupted'].includes(task.status);
 const name=task.inputPath.split(/[\\/]/).pop()||task.inputPath;
 return <article className="media-task-row"><div className="media-task-heading"><div><strong>{name}</strong><span>{operations[task.type]} · {task.request.outputFormat.toUpperCase()}</span></div><span className={task.status==='failed'?'error-text':'media-status'}>{task.status==='completed'?<Check size={15} aria-hidden="true"/>:busy?<Loader2 size={15} className="spin" aria-hidden="true"/>:null}{labels[task.status]}</span></div><p className="help">{task.phase}{task.request.batchId&&' · 批量任务'}{task.request.sourceDownloadId&&' · 下载完成自动处理'}</p>
 {busy&&<><progress aria-label={`${name}处理进度`} max={100} {...(task.progress==null?{}:{value:task.progress})}/><div className="media-progress-line"><span>{task.progress==null?'进度未知':`${task.progress.toFixed(1)}%`} · {formatMediaTime(task.processedTime)} / {formatMediaTime(task.totalDuration)}</span><span>{task.speed==null?'速度未知':`${task.speed.toFixed(1)}x`} · {task.eta==null?'剩余时间未知':`预计剩余 ${Math.ceil(task.eta)} 秒`}</span></div></>}
 {task.error&&<p className="error-text" role="alert">{task.error}</p>}{task.outputPath&&<p className="media-output-path" title={displayMediaPath(task.outputPath)}>{displayMediaPath(task.outputPath)}</p>}
 <div className="media-task-actions">{busy&&<button className="secondary" onClick={()=>void act('cancel_media_task',{id:task.id})}><X size={15} aria-hidden="true"/>取消</button>}{retry&&<button className="secondary" onClick={()=>void act('retry_media_task',{id:task.id})}><RefreshCw size={15} aria-hidden="true"/>重新开始</button>}{task.status==='completed'&&<button className="secondary" onClick={()=>void act('open_media_output',{id:task.id,folder:false})}><Play size={15} aria-hidden="true"/>打开文件</button>}<button className="text-button" onClick={()=>void act('open_media_output',{id:task.id,folder:true})}><FolderOpen size={15} aria-hidden="true"/>打开目录</button></div>{!!task.logs.length&&<details className="task-logs"><summary>技术详情（已脱敏）</summary><pre>{task.logs.join('\n')}</pre></details>}</article>;
}
